name: FriskStick
version: Beta 1.0
description: Allows a player to frisk people for drugs and other contraband.
main: friskstick.main.FriskStick
authors: [domingocool, dchaosknight]
website: http://dev.bukkit.org/bukkit-plugins/friskstick/
softdepend: [Essentials]
commands:
  friskstick:
    description: Help command for the plugin.
    aliases: fs
    permission: friskstick.help.basic
    usage: /friskstick
  comply:
    description: Allows a player to comply with a frisk request.
    permission: friskstick.comply
    usage: /comply
  report:
    description: Allows a player to report someone for drugs.
    permission: friskstick.report.send
    usage: /report <player>
  showreports:
    description: Allows a player to view all reports currently not investigated.
    permission: friskstick.report.show
    usage: /showreports
permissions:
  friskstick.*:
    description: Gives access to all permissions.
    default: op
    children:
      friskstick.report.*: true
      friskstick.comply: true
      friskstick.help.advanced: true
      friskstick.frisk: true
      friskstick.bypass: true
  friskstick.report.*:
    description: Gives all report permissions.
    default: op
    children:
      friskstick.report.send: true
      friskstick.report.receive: true
      friskstick.report.show: true
  friskstick.report.send:
    description: Allows a player to submit reports.
    default: true
  friskstick.report.receive:
    description: Allows a player to receive reports.
    default: op
  friskstick.report.show:
    description: Allows a player to use /showreports.
    default: op
  friskstick.comply:
    description: Allows a player to comply to frisk requests.
    default: true
  friskstick.help.advanced:
    description: Provides all commands available in the plugin when /friskstick is used.
    default: op
  friskstick.help.basic:
    description: Provides only commands that most players would have access to in the help menu.
    default: true
  friskstick.frisk:
    description: Allows a player to frisk.
    default: op
  friskstick.bypass:
    description: Allows a player to bypass frisking.
    default: op